### ISSUE TITLE
broken in react 15.4

### ISSUE THREAD

**Issue by ianstormtaylor** [vleletko/react-frame-aware-selection-plugin#4]
@vleletko this module seems to break now with React `15.4`

**Comment by saymy** [comment]
+1
**This module does not work in react 15.3. 2. Warnings are as follows:**

> `Warning: A component is `contentEditable` and contains `children` managed by React. It is now your responsibility to guarantee that none of those nodes are unexpectedly modified or duplicated. This is probably not intentional.`

**Comment by vleletko** [comment]
@ianstormtaylor, looks like they moved the event related code to react-dom in 15.4. Will make related change to plugin. 

@saymy, I don't think it is related to event system,
 basicly here they say that since element contents could be edited by user, React may be unable to apply virtual-dom diff.

**Comment by vleletko** [comment]
@ianstormtaylor,
new version in npm
