### ISSUE TITLE
Question: How to stop parent's window event propogation?

### ISSUE THREAD

**Issue by mtuchkov** [vleletko/react-frame-aware-selection-plugin#5]
Hi @vleletko,

I use your plugin to run Slate Editor in iframe, but in case is slightly different. 
I don't want Slate editor to loose the focus if i click on any UI element outside of the iframe with the editor. 

I would appreciate it if you can give me a clue what can I change in the plugin's behavior to do that.

**Comment by vleletko** [comment]
Hi @mtuchkov, 
 If I got you right, I am afraid you can't do it with this library. This library is small fix in react event propagation, to make react onSelect event work correctly in iframe environment. 

Can you describe your use case? Maybe we can figure out a solution for it if I will know a little more about the actual problem.

**Comment by mtuchkov** [comment]
Hi @vleletko,
I'm sorry for the late answer.
Yes, you are right that this plugin doesn't exactly solve my problem, but I guess I have to do something very similar. 

So, the scenario is this: the editor is located on the page and the entire page is in the iframe. But the toolbar is outside of the iframe. So, the goal is when the cursor moves to the toolbar and I click toolbar control's elements including input elements I don't want to loose focus within the iframe, so that the use can see what is selected when he is clicking or entering something on the toolbar. 

As you know, Slate editor doesn't work with deafault plugin at all. I works with this one, which is great, it doesn't even loose the Slate's selection when I click toolbar elements, but it still looses the focus, so the user cannot see what piece of text will be changed if he clicks the B (Bold) button, for instance. 

In simple cases I can just return focus to the slate editor after the change is done, but in more complex cases, when a user is editing the hyperlink, for instance, it won't work.

The ultimate goal is completly ignore any event that is happening in master window. I'm not sure if that is possible although. 

If you have an idea how can I tune this plugin to ignore the parent's window focus events at least that would help a lot.

**Comment by mtuchkov** [comment]
One important thing I forgot to mention. 
If I use your library slate works fine, but I loose focus as I described above, **but!**
If I do not use the frame-aware plugin, selection doesn't work, but at the same time I can click on elements on the parent window, **and** I do not loose the focus within the iframe.

**Comment by vleletko** [comment]
@mtuchkov 

 Couple thoughts:
 - Is this issue reproducible if you put toolbar inside the IFrame?
- Do you use mouseDown event?
- Do you call ```preventDefault``` on event in toolbar handlers?

I tried to reproduce your issue in slate's examples page (but quite older version) by default it works fine with the toolbar inside/outside an iframe. Maybe this will give some clues.  

If above does not help, can create some example page with this issue?

**Comment by mtuchkov** [comment]
Well, yes, it seems like I need to debug my own code better to figure out why its current behavior is different from the slate's example.  

Thank you for your help Vladimir! Will let you know if I find something interesting.
