### ISSUE TITLE
version 2.0.0 files in /dist should be transpiled

### ISSUE THREAD

**Issue by cmmartin** [vleletko/react-frame-aware-selection-plugin#8]
The version of the files in `/dist` is the same as the version in `/src` on npm. I think the files in `/dist` should be run through babel first. Otherwise, the user has to either transpile their `node_modules` or they get errors about flow types in the `/dist` files

```
ERROR in ./node_modules/react-frame-aware-selection-plugin/dist/isTextInputElement.js
Module parse failed: ./node_modules/react-frame-aware-selection-plugin/dist/isTextInputElement.js Unexpected token (16:23)
You may need an appropriate loader to handle this file type.
```

**Comment by vleletko** [comment]
@cmmartin thank you,
should be fixed in 2.0.2
